---
title: '2019-04-10'
author: "林茂廷"
date: "4/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(stringr)
library(lubridate)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(stringr)
library(lubridate)
```
```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord
studentRecord[["姓名"]]
studentRecord[["學年平均成績"]][[3]]

```

```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)
```

```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```

```{r}
plasticContainer[["greenBox"]] 
plasticContainer[[1]]
```
```{r}
plasticContainer[["greenBox"]][[1]]
```

```{r}
list(
  greenBox=c("paper","scissor"),
  redBox=c(1,3,2.5)
)
```
```{r}
extract1 <- plasticContainer[c("greenBox")]
class(extract1)
```
#取一群
```{r}
extract2 <- plasticContainer[[c("greenBox")]]
class(extract2)
```
```{r}
extract1[[1]][[1]]
extract2[[1]]
```
```{r}
length(plasticContainer)
plasticContainer[c(T,F,T)]
```
```{r}
成績單[c(FALSE,TRUE,TRUE)]
```
```{r}
your_github_username <- "locker-dc"
your_practice_reponame <- "107-2-inclass-practice"
library(httr)
library(stringr)
str_replace_all(
  "https://api.github.com/repos/:owner/:repo/commits",
  c(
    ":owner"=your_github_username,
    ":repo"=your_practice_reponame
    )
  ) -> commitCheckStatement
commitCheckStatement
commitCheck <- content(GET(commitCheckStatement))
```
```{r}
commitCheck[[4]][["commit"]][["committer"]][["date"]]
```
```{r}
install.packages("plotly")
```
```{r}
download.file("https://github.com/tpemartin/github-data/blob/master/plotly_4070_neda.Rda?raw=true",destfile = "plotly_4070_neda.Rda")
load("plotly_4070_neda.Rda")
library(plotly)
plotly_4070_neda
```
```{r}
plotly_4070_neda$x$layout$shapes[[1]]$opacity<-0.8
plotly_4070_neda
```
```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/podcastcompetition3.csv")
str_replace(filmVotingData$請選擇你最喜歡的影片二部,", by"," by") -> favoriteTwo
birthday <- filmVotingData$`出生西元年月日（驗證本人用）`
timeStamp <- filmVotingData$Timestamp
```
# 現今符號可以取代 [[]]來做選取
```{r}
library(stringr)
str_split(favoriteTwo,", ") -> favoriteTwoList # 將選擇的兩片split成兩個元素
unlist(favoriteTwoList) -> allVotes # 將list堆疊成atomic vector
table(allVotes) # 計算每個類別的次數
```
```{r}
str_length(birthday)
logiCorrect <- str_length(birthday) == 8
logiCorrect
logiCorrect[logiCorrect]
```



