---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")
```

```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
```

```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系"))
```
```{r}
typeof(studentMajors)
```

```{r}
levels(studentMajors)
```
```{r}
男生 <- factor(
  c("夜店咖", "草食男", "同性戀"))
```
```{r}
class(男生)
typeof(男生)
levels(男生)
as.integer(男生)
```



```{r}
birthPlace <- factor(
  c("台北市", "台北市", "台中市", "台中市", "台中市"))
```

```{r}
class(birthPlace)
typeof(birthPlace)
levels(birthPlace)
as.integer(birthPlace)
```
```{r}
library(lubridate)
```
```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53")
```
```{r}
library(lubridate)
```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
class(dtObject)
```
```{r}
typeof(dtObject)
```

```{r}
as.double(dtObject)
```

```{r}
Sys.timezone()
```

```{r}
twDateTime <- ymd_hms ("2019-03-18 14:04:00", tz="Asia/Taipei")
twDateTime
```

```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
LisbonDateTime
```
```{r}
typeof(twDateTime)
as.double(twDateTime)
as.double(LisbonDateTime)
```
```{r}
as.integer (ymd("1970-01-01"))
as.integer (ymd("1970-01-02"))
as.integer (ymd("2019-03-11"))
```

```{r}
Sys.timezone()
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
LisbonDateTime

typeof(twDateTime)
as.double(twDateTime)
typeof(LisbonDateTime)
as.double(LisbonDateTime)



library(lubridate)
dt1object <- mdy_hms("3/14/2019 08:18:47", tz="Asia/Taipei")
dt1bjectVector<-mdy_hms(
  c("3/14/2019 08:18:47",
    "3/14/2019 08:18:47")
)

dt1object


library(lubridate)
testdatetime1 <- ymd("2018-09-11")
testdatetime1

testdatetime2 <- mdy("March 3, 2019")
testdatetime2

```
```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
```
```{r}
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
a+aL
a-b
a*b
a/b
a+bL
```
```{r}
class(a+aL)
class(a*b)
```
```{r}
a^b
a %% b
```
```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
twDateTime+9487
twDateTime2 <- ymd_hms("2019-03-18 14:14:00", tz="Asia/Taipei")
twDateTime2 - twDateTime
```
```{r}
startingDate <- ymd("2000-02-17")
startingDate + years(1)
startingDate + dyears(1)
```
```{r}
x <- 5
y <- 7
x2 <- c(1,5,10)
y2 <- c(-1,5,20)
```

```{r}
x > y
x == y
x < y
x >= y
x >x2
x < y2
```
```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4
```
```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")
is.na(x2)
is.na(y3)
```






