---
title: '2019-05-08'
author: "d chen"
date: "5/08/2019"
output: html_document
---
{r ans1}
# logicBig
logicBig <- as.integer(x)>50
logicBig


## 2 list
建立一個答案物件compoundObject, 其中`compoundObject[[1]]`會得到數字1 (numeric class), `compoundObject[[2]]`會得到字串"hello"(character class),`compoundObject[[3]]`會得到邏輯TRUE (logical class)。 
{r ans2}
# compoundObject
compoundObject <- list(
  1,"hello","True"
)
compoundObject


## 3 UTC與時區
執行以下程式得到以UTC時區輸入的日期時間字串（submitTime）
{r data3}
load("submitTime.Rda")
請將它改成以America/New_York時區顯示的「character class」文字字串，並存在答案物件nyTime。答案物件請寫在最後一行。（注意答案物件class必修為character）
{r ans3}
# nyTime
submitTime <- mdy_hms(submitTime)
nyTime <- with_tz(submitTime,tz="America/New_York")
as.character(nyTime)
nyTime

## 4 map
有時我們會需要對list裡的每個元素取出相同位置的值，例如以下的a物件，其中對於「學號」「成績」元素的值，相同位置來自相同學生。如果我們想對每個元素取相同位置的值出來，我們可以用purrr套件裡的`map()`進行操作，方式為`map(a,~.ObjectExtraction)`
{r}
a <- list(
  學號=c("a23","a22","a41"),
  成績=c(88,76,82)
)
map(a,~.[[2]]) # 取出每個元素第二位
map(a,~.[c(1,3)]) # 取出每個元素第一及第三位
map(a,~.[c(T,F,T)]) # 取出每個元素第一及第三位

請執行以下程式隨機產生一位學生在15門課的成績及學分數。
{r data4}
randomGrades <- sample(40:80,15,replace = T)
randomCredits <- sample(0:3,15,replace=T)
data3 <- list(
  成績=randomGrades,
  學分數=randomCredits
)

請選出成績大於等於60的資料並存在passData這個帶有「成績」及「學分數」的list物件。此題答案物件為passData。
{r ans4}
# passData
passlogic <- data3[[1]] >= 60
passdata <- map(data3,~.[passlogic])
passdata


## 5
執行以下程式產生台灣民國年月字串物件twDates。
{r data5}
sample(99:103,15,replace = T)-> yy
sample(1:12,replace=T)-> mm
str_c("民國",str_pad(yy,3,"left","0"),"年",mm,"月") -> twDates
# twDates

### 5.1 去除字元
請將twDates中的"民國"及"月"都去除，並存在twDates2答案物件，如："民國099年2月"會變成"099年2"。
{r ans51}
# twDates2
twDates2 <- str_replace_all(twDates,"民國","")
twDates2 <- str_replace_all(twDates2,"月","")
twDates2

### 5.2 取出年份
取出民國年的並加上1911年轉成西元年，將此年份存在答案物件westYears裡（class為integer）。(hint: `str_split()`可分割字串,再使用第3題取出你要的部份)
{r ans52}
# westYears
year1 <- str_sub(twDates2,1,3)
year1 <- as.integer(year1)
westYears <- year1+1911
westYears

### 5.3 西元年月日
將twDates民國年月轉成date class的西元年月日，原始資料沒有日，請設定成每月1日。例如："民國100年5月"會轉成2011-05-01的date class日期。答案請存westDates答案物件。

{r ans53}
# westDates
datedata <- str_c(westYears,"-",mm,"-",01)
westDates <- ymd(datedata)
westDates

